site_name: Angry Shader Forge Docs

nav: 
  - Home: index.md
  - Deep Dive: core-concept.md
  - Node Refrence: nodes.md
  - Examples: examples.md

theme:
    name: material
    palette:
        scheme: slate
        primary: green
    
