site_name: Angry Shader Forge Docs

nav: 
  - Home: index.md
  - Deep Dive: core-concept.md
  - Node Refrence: 
      - All Nodes: nodes.md
      - Lerp Deep Dive: nodes/lerp.md
  
  - Examples: examples.md
  - Change Log: changelog.md

theme:
    name: material
    palette:
        scheme: slate
        primary: green
    
